FROM node:18 AS build
WORKDIR /app

COPY package*.json ./
ARG REACT_APP_API_URL
ARG REACT_APP_API_LOCAL_URL

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_API_LOCAL_URL=$REACT_APP_API_LOCAL_URL

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
